//import ExternalServices from "./externalServices.js";
//import ProductList from "./productList.js";
import { loadHeaderFooter } from "./utils.js";
//const externalServices = new ProductData("tents");
//const data = externalServices.getData();
//const ul = document.querySelector(".product-list");
//const template = document.querySelector("#product-card-template");
//const productList = new ProductList("tents", ul, data, template);
//productList.init();
loadHeaderFooter("#main-header", "#main-footer");
